# Generated by Django 4.2.7 on 2023-11-13 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='book/images/')),
                ('copies', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('Disponível', 'a'), ('Indisponível', 'b')], default='Disponível', max_length=12)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='category.category')),
                ('users', models.ManyToManyField(blank=True, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
